# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@5.1
  coveralls: coveralls/coveralls@2.1.1

commands:
  setup_deps:
    parameters:
      node:
        type: string
    steps:
      - node/install:
          node-version: << parameters.node >>
      - run: npm ci

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  test:
    parameters:
      node:
        type: string
    executor: base
    steps:
      - checkout
      - setup_deps:
          node: << parameters.node >>
      - run: npm run test
      - coveralls/upload:
          parallel: true
          flag_name: test-<< parameters.node >>
          verbose: true

  lint:
    executor: base
    steps:
      - checkout
      - setup_deps:
          node: "stable"
      - run: npm run lint

  fmt:
    executor: base
    steps:
      - checkout
      - setup_deps:
          node: "stable"
      - run: npm run fmt:check

  result:
    executor: base
    steps:
      - run: echo ok
      - coveralls/upload:
          parallel_finished: true
          carryforward: "test-16,test-18,test-19,test-20"

workflows:
  build:
    jobs:
      - fmt
      - lint
      - test:
          matrix:
            parameters:
              node: ["16", "18", "19", "20"]
      - result:
          requires:
            - fmt
            - lint
            - test
