# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@5.1

commands:
  get_deps:
    parameters:
      node:
        type: string
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-node<< parameters.node >>-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-node<< parameters.node >>

  save_deps:
    parameters:
      node:
        type: string
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node<< parameters.node >>-{{ checksum "package.json" }}

  install_deps:
    steps:
      - run: yarn install --frozen-lockfile

  setup_deps:
    parameters:
      node:
        type: string
    steps:
      - get_deps:
          node: << parameters.node >>
      - node/install:
          node-version: << parameters.node >>
          install-yarn: true
      - install_deps
      - save_deps:
          node: << parameters.node >>

  run_test:
    steps:
      - run: yarn test

  run_lint:
    steps:
      - run: yarn lint

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  test:
    parameters:
      node:
        type: string
    executor: base
    steps:
      - checkout
      - setup_deps:
          node: << parameters.node >>
      - run_test

  lint:
    executor: base
    steps:
      - checkout
      - setup_deps:
          node: "20"
      - run_lint

workflows:
  build:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              node: ["14", "16", "18", "19", "20"]
